use genpdf::elements;
use genpdf::fonts;
use chrono::Local;
use log::info;

pub struct ReportGenerator;

impl ReportGenerator {
    pub fn generate_markdown(session_id: &str, commands: &Vec<String>) -> String {
        let mut report = format!("# VEGA Session Report: {}\n", session_id);
        report.push_str(&format!("Date: {}\n\n", Local::now().to_rfc3339()));
        
        report.push_str("## Execution Log\n");
        for cmd in commands {
            report.push_str(&format!("- `{}`\n", cmd));
        }
        
        report.push_str("\n---\n*Generated by VEGA*");
        report
    }

    pub fn generate_pdf(filename: &str, content: &str) -> Result<(), String> {
        info!("📄 Generating PDF report: {}", filename);
        
        let font_family = fonts::from_files("assets/fonts", "LiberationSans", None)
            .map_err(|_| "Font load failed (assets/fonts/LiberationSans... missing?)".to_string())?; // Simple fallback check needed

        let mut doc = genpdf::Document::new(font_family);
        doc.set_title("VEGA Report");
        
        let mut decorator = genpdf::SimplePageDecorator::new();
        decorator.set_margins(10);
        doc.set_page_decorator(decorator);

        doc.push(elements::Paragraph::new("VEGA Implementation Report"));
        doc.push(elements::Break::new(1.5));
        doc.push(elements::Paragraph::new(content));

        doc.render_to_file(filename)
            .map_err(|e| format!("PDF render failed: {}", e))?;
            
        Ok(())
    }
}
