use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct SreReport {
    pub session_id: i64,
    pub timestamp: String,
    pub emotional_summary: String,
    pub issue: String,
    pub cause: String,
    pub solution: String,
    pub forecast: String,
    pub result: String,
}

impl SreReport {
    pub fn new(session_id: i64) -> Self {
        Self {
            session_id,
            timestamp: chrono::Local::now().to_rfc3339(),
            emotional_summary: String::from("No data analyzed yet."),
            issue: String::from("-"),
            cause: String::from("-"),
            solution: String::from("-"),
            forecast: String::from("-"),
            result: String::from("-"),
        }
    }

    pub async fn generate_from_lineage(
        session_id: i64, 
        lineage: &[crate::storage::db::DecisionRecord]
    ) -> anyhow::Result<Self> {
        if lineage.is_empty() {
            return Ok(Self::new(session_id));
        }

        let mut report = Self::new(session_id);
        
        // 1. Data Aggregation for AI
        let mut context_str = String::new();
        for (i, rec) in lineage.iter().enumerate() {
            context_str.push_str(&format!(
                "Event #{}:\nRequest: {}\nIntent: {}\nCommand: {}\nResult: {}\n\n",
                i + 1, rec.user_request, rec.intent, rec.generated_command, rec.execution_result
            ));
        }

        // 2. Call AI for Summarization (Using SmartRouter)
        let prompt = format!(
            r#"As a Senior SRE, analyze the following session data and generate a technical report in the 5-step SRE format.
Language: Korean

Data:
{}

Output JSON Format:
{{
  "emotional_summary": "One-line emotional impact",
  "issue": "Summary of problems",
  "cause": "Root cause analysis",
  "solution": "Actions taken",
  "forecast": "Long-term impact",
  "result": "Final outcome"
}}
"#, context_str);

        // We use a dummy SystemContext for the router
        let dummy_ctx = crate::context::SystemContext::collect();
        
        match crate::ai::router::SmartRouter::generate_with_fallback(&dummy_ctx, &prompt, None).await {
            Ok(json_str) => {
                if let Ok(res) = serde_json::from_str::<serde_json::Value>(&json_str) {
                    report.emotional_summary = res["emotional_summary"].as_str().unwrap_or("Done").to_string();
                    report.issue = res["issue"].as_str().unwrap_or("-").to_string();
                    report.cause = res["cause"].as_str().unwrap_or("-").to_string();
                    report.solution = res["solution"].as_str().unwrap_or("-").to_string();
                    report.forecast = res["forecast"].as_str().unwrap_or("-").to_string();
                    report.result = res["result"].as_str().unwrap_or("-").to_string();
                }
            },
            Err(e) => eprintln!("⚠️ AI Report Generation Failed: {}", e),
        }

        Ok(report)
    }

    pub fn render_markdown(&self) -> String {
        format!(
            r#"# 🚀 VEGA SRE Session Report - Session #{}

## 📊 Emotional Summary
"{}"

---

## 📄 SRE 5-Step Analysis

### 1. 현안 및 문제 (Issue)
{}

### 2. 근본 원인 분석 (Cause)
{}

### 3. 해결 방안 (Solution)
{}

### 4. 도입 결과 예측 (Forecast)
{}

### 5. 최종 수행 결과 (Result)
{}

---
**"Report generated by VEGA SRE Intelligence."**
"#,
            self.session_id,
            self.emotional_summary,
            self.issue,
            self.cause,
            self.solution,
            self.forecast,
            self.result
        )
    }
}
